name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.2.0
          cache-dependency-path: package-lock.json
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - id: changelog
        run: >+
          previousTag=$(git tag -l --sort=-version:refname | grep -v -- '-.*' | head -n 2 | tail -n 1)
          changelog=$(npm run changelog -- $previousTag)
          echo "changelog=${changelog}" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        id: create-release

        with:
          script: >+
            const tag = core.getInput('tag')
            const name = core.getInput('name')
            const body = ${{ steps.changelog.outputs.changelog }}
            const draft = false
            const prerelease = false
            const response = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: name,
              body: body,
              draft: draft,
              prerelease: prerelease
            })
          result-encoding: string
#      - run: git config --global user.email "donato@wolfisberg.dev"
#      - run: git config --global user.name "Releaser"
#      - run: npm version prerelease -m "Create prerelease version %s"
#      - run: git push && git push --tags
